#include <stdio.h>
#include <stdlib.h>
#include <level_zero/ze_api.h>
#include "./ze_utils.h"

//  _
// |_)  _  |  _  ._ ._  |  _. _|_  _
// |_) (_) | (/_ |  |_) | (_|  |_ (/_
//                  |

/* - - - -
IO
- - - - */
int read_from_binary(unsigned char **output, size_t *size, const char *name) {
  FILE *fp = fopen(name, "rb");
  if (!fp) {
    return -1;
  }

  fseek(fp, 0, SEEK_END);
  *size = ftell(fp);
  fseek(fp, 0, SEEK_SET);

  *output = (unsigned char *)malloc(*size * sizeof(unsigned char));
  if (!*output) {
    fclose(fp);
    return -1;
  }

  fread(*output, *size, 1, fp);
  fclose(fp);
  return 0;
}

/* - - - -
OpenCL Error
- - - - */

const char *getErrorString(ze_result_t error)
{
switch(error){
    // run-time and JIT compiler errors
 case ZE_RESULT_SUCCESS: return "ZE_RESULT_SUCCESS";
 case ZE_RESULT_NOT_READY: return "ZE_RESULT_NOT_READY";
 case ZE_RESULT_ERROR_DEVICE_LOST: return "ZE_RESULT_ERROR_DEVICE_LOST";
 case ZE_RESULT_ERROR_OUT_OF_HOST_MEMORY: return "ZE_RESULT_ERROR_OUT_OF_HOST_MEMORY";
 case ZE_RESULT_ERROR_OUT_OF_DEVICE_MEMORY: return "ZE_RESULT_ERROR_OUT_OF_DEVICE_MEMORY";
 case ZE_RESULT_ERROR_MODULE_BUILD_FAILURE: return "ZE_RESULT_ERROR_MODULE_BUILD_FAILURE";
 case ZE_RESULT_ERROR_INSUFFICIENT_PERMISSIONS: return "ZE_RESULT_ERROR_INSUFFICIENT_PERMISSIONS";
 case ZE_RESULT_ERROR_NOT_AVAILABLE: return "ZE_RESULT_ERROR_NOT_AVAILABLE";
 case ZE_RESULT_ERROR_UNINITIALIZED: return "ZE_RESULT_ERROR_UNINITIALIZED";
 case ZE_RESULT_ERROR_UNSUPPORTED_VERSION: return "ZE_RESULT_ERROR_UNSUPPORTED_VERSION";
 case ZE_RESULT_ERROR_UNSUPPORTED_FEATURE: return "ZE_RESULT_ERROR_UNSUPPORTED_FEATURE";
 case ZE_RESULT_ERROR_INVALID_ARGUMENT: return "ZE_RESULT_ERROR_INVALID_ARGUMENT";
 case ZE_RESULT_ERROR_INVALID_NULL_HANDLE: return "ZE_RESULT_ERROR_INVALID_NULL_HANDLE";
 case ZE_RESULT_ERROR_HANDLE_OBJECT_IN_USE: return "ZE_RESULT_ERROR_HANDLE_OBJECT_IN_USE";
 case ZE_RESULT_ERROR_INVALID_NULL_POINTER: return "ZE_RESULT_ERROR_INVALID_NULL_POINTER";
 case ZE_RESULT_ERROR_INVALID_SIZE: return "ZE_RESULT_ERROR_INVALID_SIZE";
 case ZE_RESULT_ERROR_UNSUPPORTED_SIZE: return "ZE_RESULT_ERROR_UNSUPPORTED_SIZE";
 case ZE_RESULT_ERROR_UNSUPPORTED_ALIGNMENT: return "ZE_RESULT_ERROR_UNSUPPORTED_ALIGNMENT";
 case ZE_RESULT_ERROR_INVALID_SYNCHRONIZATION_OBJECT: return "ZE_RESULT_ERROR_INVALID_SYNCHRONIZATION_OBJECT";
 case ZE_RESULT_ERROR_INVALID_ENUMERATION: return "ZE_RESULT_ERROR_INVALID_ENUMERATION";
 case ZE_RESULT_ERROR_UNSUPPORTED_ENUMERATION: return "ZE_RESULT_ERROR_UNSUPPORTED_ENUMERATION";
 case ZE_RESULT_ERROR_UNSUPPORTED_IMAGE_FORMAT: return "ZE_RESULT_ERROR_UNSUPPORTED_IMAGE_FORMAT";
 case ZE_RESULT_ERROR_INVALID_NATIVE_BINARY: return "ZE_RESULT_ERROR_INVALID_NATIVE_BINARY";
 case ZE_RESULT_ERROR_INVALID_GLOBAL_NAME: return "ZE_RESULT_ERROR_INVALID_GLOBAL_NAME";
 case ZE_RESULT_ERROR_INVALID_KERNEL_NAME: return "ZE_RESULT_ERROR_INVALID_KERNEL_NAME";
 case ZE_RESULT_ERROR_INVALID_FUNCTION_NAME: return "ZE_RESULT_ERROR_INVALID_FUNCTION_NAME";
 case ZE_RESULT_ERROR_INVALID_GROUP_SIZE_DIMENSION: return "ZE_RESULT_ERROR_INVALID_GROUP_SIZE_DIMENSION";
 case ZE_RESULT_ERROR_INVALID_GLOBAL_WIDTH_DIMENSION: return "ZE_RESULT_ERROR_INVALID_GLOBAL_WIDTH_DIMENSION";
 case ZE_RESULT_ERROR_INVALID_KERNEL_ARGUMENT_INDEX: return "ZE_RESULT_ERROR_INVALID_KERNEL_ARGUMENT_INDEX";
 case ZE_RESULT_ERROR_INVALID_KERNEL_ARGUMENT_SIZE: return "ZE_RESULT_ERROR_INVALID_KERNEL_ARGUMENT_SIZE";
 case ZE_RESULT_ERROR_INVALID_KERNEL_ATTRIBUTE_VALUE: return "ZE_RESULT_ERROR_INVALID_KERNEL_ATTRIBUTE_VALUE";
 case ZE_RESULT_ERROR_INVALID_COMMAND_LIST_TYPE: return "ZE_RESULT_ERROR_INVALID_COMMAND_LIST_TYPE";
 case ZE_RESULT_ERROR_OVERLAPPING_REGIONS: return "ZE_RESULT_ERROR_OVERLAPPING_REGIONS";
 case ZE_RESULT_ERROR_UNKNOWN: return "ZE_RESULT_ERROR_UNKNOWN";
    default: return "Unknown L0 error";
 }
}

void check_error(ze_result_t error, char const *name) {
    if (error != ZE_RESULT_SUCCESS) {
        fprintf(stderr, "Non-successful return code %d (%s) for %s.  Exiting.\n", error, getErrorString(error), name);
        exit(EXIT_FAILURE);
    }
}

void exit_msg(char const *str){
        fprintf(stderr, "%s \n", str);
        exit(EXIT_FAILURE);
}

